MOUSEKEY_ENABLE 	= no			# Mouse keys disabled for this layout
OLED_ENABLE				= yes
OLED_DRIVER   	  = SSD1306
LTO_ENABLE      	= yes			# Optimization for smaller firmware footprint
VIA_ENABLE				= yes			# Enable VIA for graphical modifications of the layout
COMBO_ENABLE			= yes
RGBLIGHT_ENABLE		= yes
RGB_MATRIX_ENABLE	= no			# Better RGB effects
BOOTMAGIC_ENABLE  = yes 			# Allow booting into bootloader mode from combo key on startup
TAP_DANCE_ENABLE  = yes
BOOTLOADER 				= atmel-dfu